### ISSUE TITLE
Addon doesn't work with firefox 42

### ISSUE THREAD

**Issue by DavidMcKenneyBarschall** [shhac/CookieExFilter#1]
"Filter" mode always shows an empty list of exceptions and "search" mode doesn't search.

When attempting to change permissions on an exception, an error appears: "invalid host name: please enter a valid host name"

**Comment by shhac** [comment]
Filtering should now be fixed. Please report back if there are still more issues - thanks!

**Comment by DavidMcKenneyBarschall** [comment]
The 1.0.3 build here works for me.

... it could do with getting pushed to the Mozilla website and signed, though.

**Comment by shhac** [comment]
The review process takes time, as soon as Mozilla are happy it will show up
